# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# --------------------------------------------------------------------------------------------
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer
  namespace: kafka
spec:
  containers:
    - image: $PRODUCER_IMAGE
      name: kafka-producer
      command:
        - /produce
      env:
        - name: TOPIC
          value: $TOPIC
        - name: MSG
          value: "Azure Confidential Computing"
        - name: PUBKEY
          value: |-
            $PUBKEY
      resources:
        limits:
          memory: 1Gi
          cpu: 200m
